import { ApprovalQueue, ViemAdapter, createGuard } from "@agentctl/core";
import { serveControlPlane } from "./dist/index.js";
import { generatePrivateKey } from "viem/accounts";
import { parseUnits } from "viem";
const USDC="0x036CbD53842c5426634e7929541eC2318f3dCF7e", A="0x1111111111111111111111111111111111111111", B="0x2222222222222222222222222222222222222222";
const queue=new ApprovalQueue();
const guard=await createGuard({wallet:new ViemAdapter({privateKey:generatePrivateKey()}),policy:{agentId:"a",anomalyThreshold:0.8,anomalyAction:"escalate",rules:[{type:"allowlist",mode:"recipients",entries:[A.toLowerCase()],enforce:true}]},approvalQueue:queue,circuitBreaker:{windowSeconds:60,maxBlocks:2}});
const server=await serveControlPlane(guard,{port:0});
const base=`http://127.0.0.1:${server.address().port}`;
console.log("health:", JSON.stringify(await (await fetch(`${base}/health`)).json()));
const ev=await (await fetch(`${base}/evaluate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({request:{intent:"x",amount:parseUnits("1",6).toString(),token:USDC,recipient:B,chain:"eip155:84532"}})})).json();
console.log("evaluate verdict:", ev.decision.verdict);
guard.circuitBreaker.record("block",false); guard.circuitBreaker.record("block",false);
console.log("breaker:", JSON.stringify(await (await fetch(`${base}/breaker`)).json()));
queue.enqueue({intent:"x",amount:parseUnits("15",6),token:USDC,recipient:A,chain:"eip155:84532",agentId:"a"},{verdict:"escalate",riskScore:0.5,checks:[],reason:""},60);
const list=await (await fetch(`${base}/approvals`)).json();
console.log("approvals pending:", list.pending.length, "-> approve:", (await (await fetch(`${base}/approvals/${list.pending[0].id}/approve`,{method:"POST"})).json()).resolved);
server.close(); process.exit(0);
